export default {
    drawerNav: "drawerNav",
    mainNav: "mainNav",
    signUpNav: "signUpNav",
    tabNav: "tabNav",
    login: "loginScreen",
    onBoarding: "onBoardingScreen",
    licenseList: "licenseList",
    home: "homeScreen",
    hunting: "huntingScreen",
    fishing: "fishingScreen",
    weather: "weatherScreen",
    solunar: "solunarScreen",
    crss: "crssScreen",
    signUp: "signUpScreen",
    addProfile: "addProfileScreen",
    addPrimaryProfile: "addPrimaryProfileScreen",
    manageProfile: "ManageProfile",
    signIn: "signIn",
    deleteAccount: "deleteAccountScreen",
};
