export default {
    signInNav: "signInNav",
    drawerNav: "drawerNav",
    mainNav: "mainNav",
    signUpNav: "signUpNav",
    tabNav: "tabNav",
    login: "loginScreen",
    onBoarding: "onBoardingScreen",
    licenseList: "licenseList",
    home: "homeScreen",
    hunting: "huntingScreen",
    fishing: "fishingScreen",
    weather: "weatherScreen",
    solunar: "solunarScreen",
    crss: "crssScreen",
    signUp: "signUpScreen",
    addProfile: "addProfileScreen",
    addPrimaryProfile: "addPrimaryProfileScreen",
    profileDetails: "profileDetailsScreen",
    manageProfile: "ManageProfile",
    signIn: "signIn",
    setting: "setting",
    deleteAccount: "deleteAccountScreen",
    forgotPasswordEnterEmail: "forgotPasswordEnterEmailScreen",
    forgotPasswordEnterValidationCode: "forgotPasswordValidationCodeScreen",
    forgotPasswordResetPassword: "forgotPasswordResetPasswordScreen",
};
